"""
SOVEREIGN DATA LAYER: Canonical Schema Definition for Capillary Nerve Center
Architectural Rationale: Single source of truth with strongly-typed event-driven architecture.
All microservices read/write through this schema, enabling cross-service intelligence.
"""

import datetime
from typing import Dict, List, Optional, Any, Literal
from pydantic import BaseModel, Field, validator
import logging

# Configure structured logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# CANONICAL EVENT TYPES - All portals must use these
EVENT_TYPES = Literal[
    'MessageReceived',
    'DataSubmitted',
    'CodeAuditRequested',
    'InsightGenerated',
    'PaymentProcessed',
    'SubscriptionUpdated',
    'ErrorOccurred'
]

# USER TIERS - Monetization framework
USER_TIERS = Literal['free', 'basic', 'premium', 'enterprise']

class UserDocument(BaseModel):
    """Unified user identity across all portals"""
    user_id: str = Field(..., description="Primary identifier (Discord ID, API key, email hash)")
    tier: USER_TIERS = Field('free', description="Monetization tier determining feature access")
    created_at: datetime.datetime = Field(default_factory=datetime.datetime.utcnow)
    updated_at: datetime.datetime = Field(default_factory=datetime.datetime.utcnow)
    stripe_customer_id: Optional[str] = Field(None, description="Stripe customer reference")
    discord_servers: List[str] = Field(default_factory=list, description="Guild IDs for network analysis")
    api_key: Optional[str] = Field(None, description="Hashed API key for REST access")
    monthly_usage: Dict[str, int] = Field(
        default_factory=lambda: {'discord': 0, 'api': 0, 'audit': 0},
        description="Usage tracking per portal"
    )
    
    @validator('user_id')
    def validate_user_id(cls, v):
        if not v or len(v) < 3:
            logger.error(f"Invalid user_id: {v}")
            raise ValueError("user_id must be at least 3 characters")
        return v
    
    class Config:
        json_encoders = {
            datetime.datetime: lambda dt: dt.isoformat()
        }

class EventDocument(BaseModel):
    """Canonical event schema - all system activity flows through this"""
    event_id: Optional[str] = Field(None, description="Auto-generated by Firestore")
    event_type: EVENT_TYPES = Field(...)
    user_id: str = Field(...)
    portal: Literal['discord', 'api', 'audit', 'dashboard'] = Field(...)
    timestamp: datetime.datetime = Field(default_factory=datetime.datetime.utcnow)
    raw_payload: Dict[str, Any] = Field(default_factory=dict)
    processed: bool = Field(False, description="Whether intelligence modules have processed this")
    metadata: Dict[str, Any] = Field(
        default_factory=lambda: {
            'ip_address': None,
            'user_agent': None,
            'processing_time_ms': None
        }
    )
    
    @validator('raw_payload')
    def validate_payload_size(cls, v):
        import json
        if len(json.dumps(v)) > 100000:  # 100KB limit
            logger.warning("Event payload exceeds 100KB, truncating metadata")
            v = {'truncated': True, 'original_size': len(json.dumps(v))}
        return v

class InsightDocument(BaseModel):
    """Structured intelligence output from processing events"""
    insight_id: Optional[str] = Field(None)
    source_event_id: str = Field(...)
    user_id: str = Field(...)
    insight_type: Literal['sentiment', 'network', 'data_quality', 'security', 'trend'] = Field(...)
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence score")
    payload: Dict[str, Any] = Field(...)
    generated_at: datetime.datetime = Field(default_factory=datetime.datetime.utcnow)
    version: str = Field("1.0.0", description="Insight generator version for backward compatibility")
    
    @validator('confidence')
    def validate_confidence(cls, v):
        if not 0 <= v <= 1:
            logger.error(f"Confidence out of bounds: {v}")
            raise ValueError("Confidence must be between 0 and 1")
        return round(v, 4)

class SubscriptionDocument(BaseModel):
    """Unified subscription management across all portals"""
    subscription_id: Optional[str] = Field(None)
    user_id: str = Field(...)
    portal_access: Dict[str, bool] = Field(
        default_factory=lambda: {'discord': False, 'api': False, 'audit': False}
    )
    monthly_cap: Dict[str, int] = Field(
        default_factory=lambda: {'discord': 100, 'api': 50, 'audit': 10}
    )
    current_usage: Dict[str, int] = Field(
        default_factory=lambda: {'discord': 0, 'api': 0, 'audit': 0}
    )
    stripe_subscription_id: Optional[str] = Field(None)
    status: Literal['active', 'past_due', 'canceled', 'incomplete'] = Field('incomplete')
    created_at: datetime.datetime = Field(default_factory=datetime.datetime.utcnow)
    renews_at: Optional[datetime.datetime] = Field(None)
    
    def check_access(self, portal: str, increment: bool = False) -> bool:
        """Check if user has access to portal, optionally incrementing usage"""
        if not self.portal_access.get(portal, False):
            logger.warning(f"User {self.user_id} attempted to access {portal} without permission")
            return False
        
        if increment:
            current = self.current_usage.get(portal, 0)
            cap = self.monthly_cap.get(portal, 0)
            if current >= cap:
                logger.warning(f"User {self.user_id} exceeded {portal} monthly cap")
                return False
            self.current_usage[portal] = current + 1
        
        return True

# Collection names as constants for type safety
COLLECTIONS = {
    'users': UserDocument,
    'events': EventDocument,
    'insights': InsightDocument,
    'subscriptions': SubscriptionDocument
}

logger.info("Canonical schema initialized with %d collection types", len(COLLECTIONS))